-- serial
create table "users"(
	"user_id" SERIAL PRIMARY KEY,
	"username" VARCHAR(100)
);

-- IDENTITY que no permite la insercion manual de id
create table "users2 "(
	"user_id" integer generated always as IDENTITY PRIMARY key,
	"username" VARCHAR(100)
);

-- IDENTITY que si permite la insercion manual
create table "users3"(
	"user_id" integer generated by default as IDENTITY PRIMARY key,
	"username" VARCHAR(100)
);

-- IDENTITY que es autoincrementado y no permite la insercion manual
create table "users4"(
	"user_id" integer generated always as IDENTITY 
	(start with 100 INCREMENT by 2),
	"username" VARCHAR(100)
);

-- llaves compuestas
create table usersDual(
	id1 int,
	id2 int,
	PRIMARY KEY (id1,id2)
);


-- uuids
create EXTENSION if not exists "uuid-ossp";
drop EXTENSION "uuid-ossp";

select gen_random_uuid();

create table users5(
	"user_id"  UUID default uuid_generate_v4() PRIMARY key,
	"username" varchar

);


--secuencias

Create SEQUENCE user_sequence;

drop sequence user_sequence;

SELECT nextval('user_sequence') currval ('user_sequence');

create table users6(
	"user_id" integer PRIMARY key DEFAULT nextval('user_sequence'),
	"username" varchar
);